/**
 * Copy em português simples — glossário de referência:
 * - previsão / prever → ação e registro do usuário (não "aposta")
 * - participação → valor financeiro (stake) em um mercado
 * - previsões → lista de posições abertas ou histórico
 * - pool / prize pool → prêmio total / volume no mercado
 * - payout → quanto você pode ganhar / ganho
 * - ROI → retorno (%)
 * - PnL → ganhos acumulados
 * - previsão da UrbanMind → indicação da IA (não "palpite" na UI)
 * - operar / terminal → prever / mercados / painel
 * - accuracy → precisão
 * - SIM/NÃO → mantidos nos botões
 */
import type { Side } from "@/store/viax-store";

export const copy = {
  common: {
    loading: "Carregando…",
  },

  nav: {
    home: "Início",
    markets: "Mercados",
    football: "Futebol",
    live: "Ao vivo",
    ranking: "Ranking",
    feed: "Feed",
    urbanmind: "UrbanMind",
    account: "Minha conta",
    settings: "Configurações",
    notifications: "Notificações",
    positions: "Minhas previsões",
    wallet: "Carteira",
    more: "Mais",
    backToApp: "Voltar ao app",
  },

  football: {
    metaTitle: "Futebol · ViaX",
    metaDescription: "Preveja o resultado de jogos: vitória do mandante, empate ou visitante.",
    title: "Futebol",
    subtitle: "Mercados 1X2 aprovados pela equipe ViaX.",
    disabled: "Mercados de futebol estão temporariamente desativados.",
    emptyTitle: "Nenhum jogo aberto",
    emptyDesc: "Novos jogos aparecem aqui após aprovação da equipe.",
    backUrban: "Ver mercados urbanos",
    backList: "Voltar aos jogos",
    notFound: "Mercado não encontrado.",
    leagueLabel: "Liga",
    badge: "Futebol",
    home: "Casa",
    draw: "Empate",
    away: "Fora",
    poolTotal: "Prêmio no mercado",
    participants: "participantes",
    placeBet: "Fazer previsão",
    stake: "Valor (BRL)",
    estPayout: "Retorno estimado",
    confirmBet: "Confirmar previsão",
    betSuccess: "Previsão registrada!",
    loginRequired: "Entre na conta para prever.",
    bettingClosed: "Apostas encerradas para este jogo.",
    settled: "Mercado liquidado:",
    insufficientBalance: "Saldo insuficiente.",
    errorGeneric: "Não foi possível registrar a previsão.",
    placing: "Processando…",
  },

  landing: {
    metaTitle: "ViaX — Trânsito, futebol e previsões da comunidade",
    metaDescription:
      "Previsões ao vivo: trânsito em São Paulo com UrbanMind AI, jogos 1X2 e mercados Sim/Não criados pela comunidade. 90% do prêmio para quem acertar.",
    ogTitle: "ViaX — Previsões ao vivo em três categorias",
    ogDescription:
      "Trânsito, futebol e mercados da comunidade. Prêmio parimutuel, ranking e criação de previsões com capa e horário de encerramento.",
    badge: "Trânsito · Futebol · Comunidade · Ao vivo",
    heroTitleLead: "Previsões ao vivo",
    heroTitleTail: "que valem prêmio — trânsito, futebol e comunidade.",
    heroBody:
      "Trânsito com mapa e UrbanMind AI, jogos 1X2 com horário de kickoff, ou crie sua própria previsão Sim/Não com capa e encerramento às 18h. Todo mundo no mesmo prêmio — 90% para quem acertar.",
    ctaEnter: "Começar agora",
    ctaMarkets: "Ver mercados",
    ctaTransito: "Trânsito",
    ctaFutebol: "Futebol",
    ctaOutros: "Outros",
    createMarketCta: "Criar previsão",
    kpiCommunity: "Previsões da comunidade",
    pillarsEyebrow: "Três formas de prever",
    pillarsTitle: "Escolha seu mercado e entre no prêmio.",
    segmentTransitoTitle: "Trânsito",
    segmentFutebolTitle: "Futebol",
    segmentOutrosTitle: "Outros",
    segmentOutrosHint: "Capa opcional · encerra no horário que você definir",
    segmentOutrosMockTime: "24 mai · 18:00",
    segmentOutrosMockQuestion: "Ex.: O Neymar será titular no amistoso?",
    liveMarketsEyebrow: "Mercados ao vivo",
    liveMarketsTitle: "Trânsito, jogos e previsões da comunidade.",
    liveMarketsBody:
      "Pools atualizam em tempo real. Cada categoria tem seu hub — entre antes do fechamento.",
    liveMarketsEmpty: "Nenhum mercado aberto agora.",
    liveMarketsBeFirst: "Seja o primeiro a criar",
    seeAllSegment: "Ver todos",
    howEyebrow: "Como funciona",
    howUrbanEyebrow: "No trânsito",
    howTitle: "Da rua para a previsão, em poucos passos.",
    step1: "1. Escolha um mercado",
    step1Desc: "Trânsito, futebol 1X2 ou previsões criadas pela comunidade.",
    step2: "2. Todo mundo prevê junto",
    step2Desc: "Traders entram no lado escolhido. As chances mudam conforme as previsões chegam.",
    step3: "3. Acompanhe ao vivo",
    step3Desc: "Mapa e UrbanMind no trânsito; placar e horário nos jogos; countdown na comunidade.",
    step4: "4. Prêmio para quem acertar",
    step4Desc: "90% do volume no mercado é dividido entre os vencedores do lado certo.",
    marketsTitle: "Mercados ao vivo em três categorias.",
    marketsBody:
      "Trânsito urbano, jogos aprovados pela equipe e previsões publicadas por traders — sempre no modelo parimutuel.",
    urbanMindLead: "No trânsito, compare sua leitura com a UrbanMind AI.",
    mapSectionEyebrow: "Trânsito em São Paulo",
    kpiVolume: "Volume no mercado",
    kpiTraders: "Participantes",
    kpiAiPrecision: "Precisão da IA (30d)",
    kpiHumanPrecision: "Precisão da comunidade",
    chartTitle: "Precisão da IA vs pessoas · 30 dias",
    mapTitle: "A cidade respira. Os mercados também.",
    prizeTotal: "Prêmio total",
    leaderboardAccuracy: "Precisão",
    leaderboardReturn: "Retorno",
    mobileTitle: "Tudo no celular.",
    mobileBody: "Preveja, acompanhe e receba alertas onde estiver.",
    ctaTerminal: "Abrir app",
    footerTerminal: "Painel",
    mockLive: "Ao vivo · ViaX",
  },

  onboarding: {
    step1Title: "O que é uma previsão?",
    step1Body:
      "No ViaX você prevê o trânsito de São Paulo: escolhe SIM ou NÃO em perguntas sobre fluxo, velocidade e congestionamento.",
    step2Title: "Como prever",
    step2Body:
      "Escolha um mercado, toque em SIM ou NÃO e defina a participação. Quanto antes você acertar, maior pode ser o que você ganha. Todo mundo prevê no mesmo prêmio.",
    step3Title: "Ganhe com precisão",
    step3Body:
      "Cada acerto melhora sua posição no ranking e desbloqueia conquistas. Use o mapa ao vivo e a UrbanMind (nossa IA) para embasar suas previsões.",
    skip: "Pular",
    next: "Próximo",
    finish: "Ver mercado em alta",
    step2Cta: "Prever SIM ou NÃO",
    step2StakeLabel: "Participação",
    step3WinLine: "Previu SIM · Acertou!",
    firstPredictionCta: "Fazer minha primeira previsão",
  },

  bet: {
    operateMarket: "Fazer previsão",
    prizeTotal: "Prêmio total agora",
    yourShare: "Sua parte das previsões",
    potentialWin: "Se ganhar, você recebe até",
    estimatedReturn: "Retorno estimado",
    poolNote: "90% do total vai para quem acertar · Resultado pela UrbanMind AI",
    operateCta: (side: Side, amount: string) =>
      `Prever ${side === "YES" ? "SIM" : "NÃO"} · ${amount}`,
    processing: "Processando...",
    resolvedTitle: "Mercado encerrado",
    resolvedResult: "Resultado oficial:",
    closedTitle: "Entradas encerradas",
    closedDesc: "Aguardando coleta UrbanMind para liquidação.",
    resolvingTitle: "Resolvendo mercado",
    resolvingDesc: "Oráculo coletando dados urbanos em tempo real.",
    disputeTitle: "Mercado em disputa",
    disputeDesc: "Validação manual em andamento. Previsões congeladas.",
    voidTitle: "Mercado cancelado",
    voidDesc: "Reembolso integral creditado na carteira.",
    imbalanceWarn: "Liquidez desequilibrada — risco de cancelamento com reembolso.",
    viewWallet: "Ver carteira",
    viewHistory: "Histórico de previsões",
    sideYes: "SIM",
    sideNo: "NÃO",
    draftTitle: "Mercado em rascunho",
    draftDesc: "Aguardando abertura oficial pelo admin.",
    confirmTitle: "Confirmar previsão",
    confirmSide: "Sua previsão",
    confirmStake: "Participação",
    confirmCancel: "Voltar",
    confirmSubmit: (side: Side, amount: string) =>
      `Confirmar ${side === "YES" ? "SIM" : "NÃO"} · ${amount}`,
    confirmFeeNote: (housePct: number, prizePct: number) =>
      `A plataforma retém ${housePct.toFixed(0)}% do prêmio; ${prizePct.toFixed(0)}% é dividido entre quem acertar.`,
    confirmReturn: "Retorno estimado se ganhar",
    placeError: "Erro ao registrar previsão",
    operateHeading: "Prever neste mercado",
    rationalePlaceholder: "Por que você está prevendo isso? (máx 140 caracteres)",
  },

  ia: {
    badgeTooltip: "Compara a previsão da UrbanMind com o que as pessoas já previram neste mercado.",
    filterLabel: "Com dica da IA",
    neutral: (side: Side) => `IA em dúvida · ${side === "YES" ? "SIM" : "NÃO"}`,
    favors: (side: Side) => `A IA indica ${side === "YES" ? "SIM" : "NÃO"}`,
    edgeLabel: "Dica da IA",
    closingWithIa: "Encerrando · dica da IA",
  },

  dashboard: {
    metaTitle: "Início · ViaX",
    metaDescription: "Seu painel com mercados ao vivo, saldo e previsão da UrbanMind AI.",
    welcomeToast: "Bem-vindo ao ViaX",
    welcomeToastDesc: "Explore mercados ao vivo ou use ⌘K para buscar.",
    greeting: (name: string) => `Olá, ${name}.`,
    balance: "Saldo",
    profit24h: "P&L hoje",
    roi: "Retorno",
    precision: "Precisão",
    precisionSub: "Últimos 30 mercados",
    gainsChart: "Seus ganhos",
    performance: "Seus ganhos",
    gainsChartHint: "Faça sua primeira previsão para ver o gráfico de ganhos.",
    actionNow: "Ação agora",
    positionLine: "Sua previsão",
    positionEst: (amount: string) => `ganho estimado ${amount}`,
    operateMarket: "Prever neste mercado",
    viewPanel: "Ver no painel",
    marketsHot: "Mercados em alta",
    openPositions: "Previsões abertas",
  },

  profile: {
    precision: "Precisão",
    totalReturn: "Retorno total",
    profit24h: "Lucro 24h",
    gains60d: "Ganhos · 60 dias",
    tabOverview: "Visão geral",
    tabPositions: "Minhas previsões",
    tabWallet: "Carteira",
    tabFavorites: "Favoritos",
    tabBadges: "Conquistas",
    tabActivity: "Atividade",
    tabSettings: "Configurações",
    badgeRoi: "Retorno acima de 100% em um mercado",
    publicHistoryHint: "Histórico disponível após previsões resolvidas",
    publicPredictionsTitle: "Últimas previsões públicas",
  },

  auth: {
    loginTitle: "Entrar na ViaX",
    loginSubtitle: "Acesse sua conta de trader com e-mail e senha.",
    signupTitle: "Criar conta",
    signupSubtitle: "Cadastro formal para prever, depositar e participar do programa de creators.",
    forgotTitle: "Recuperar senha",
    forgotSubtitle: "Enviaremos um link de redefinição para seu e-mail.",
    callbackTitle: "Confirmando acesso",
    callbackSubtitle: "Estamos validando seu link de e-mail. Aguarde um instante.",
    verifyTitle: "Confirme seu e-mail",
    verifySubtitle: "Quase lá — falta um passo para ativar sua conta.",
    verifyHint: "Abra o link que enviamos na sua caixa de entrada. Depois volte e faça login.",
    verifySent: "Enviamos um e-mail de confirmação.",
    emailLabel: "E-mail",
    passwordLabel: "Senha",
    nameLabel: "Nome exibido",
    nameMin: "Informe um nome com pelo menos 2 caracteres.",
    loginCta: "Entrar",
    signupCta: "Criar conta",
    resetCta: "Enviar link",
    loading: "Aguarde…",
    loginSuccess: "Login realizado.",
    signupSuccess: "Conta criada com sucesso.",
    resetSent: "Se o e-mail existir, você receberá instruções em instantes.",
    forgotPassword: "Esqueci minha senha",
    noAccount: "Ainda não tem conta?",
    hasAccount: "Já tem conta?",
    signupLink: "Cadastre-se",
    loginLink: "Entrar",
    backToLogin: "Voltar ao login",
    registerRequired: "Crie uma conta formal para continuar.",
    walletRegisterHint: "Depósitos e saques Pix exigem e-mail confirmado.",
    registerCta: "Criar conta",
    depositAndPlayCta: "Depositar e jogar",
    roleTrader: "Trader",
    rolePartner: "Afiliado",
    roleAdmin: "Admin",
  },

  wallet: {
    totalReturn: "Retorno total",
    lowBalance: "Saldo baixo para prever.",
    entry: "Previsão registrada",
    payout: "Ganho de mercado",
    deposit: "Depósito",
    withdraw: "Saque",
    refund: "Reembolso",
    winsPayouts: "Vitórias e ganhos",
    simulatedTitle: "Créditos promocionais",
    simulatedDepositNote:
      "Recargas rápidas da roleta são créditos de entretenimento — não substituem depósitos Pix.",
    pixTitle: "Depósitos via Pix",
    pixDepositNote:
      "Pagamentos processados com segurança. O saldo é creditado após confirmação bancária.",
    subtitle: "Saldo, movimentações e histórico de previsões.",
    predictionsTab: (count: number) => `Previsões (${count})`,
    stakeLabel: "Participação",
  },

  positions: {
    title: "Minhas previsões",
    subtitle: "Previsões em andamento com ganho estimado · histórico dos mercados já encerrados.",
    openCount: "Previsões abertas",
    totalOpen: "Total em jogo",
    estimatedGain: "Ganho estimado",
    estWin: "Se ganhar, recebe",
    estGain: "Ganho estimado",
    emptyOpen: "Nenhuma previsão aberta.",
    explore: "Explorar mercados",
    payout: "Ganho:",
    stakeLabel: "Participação",
    footballBadge: "Futebol",
    lostAnalysisTitle: "Análise da previsão perdida",
    lostAnalysisLine: "Você previu",
  },

  settings: {
    winsGains: "Vitórias e ganhos",
    platformName: "ViaX — previsões urbanas",
    intro:
      "O ViaX é um app de previsões sobre a cidade. Quase todo o dinheiro em jogo (90%) vai para quem acertar; a plataforma retém 10% para manter o serviço.",
    houseRetention: "Taxa da plataforma",
    houseRetentionValue: "10% do volume no mercado",
    adminTitle: "Resolução admin",
    adminDesc: "Mercados em disputa aguardam decisão manual antes da liquidação.",
    adminNoDisputes: "Nenhum mercado em disputa no momento.",
    adminResolved: "Mercado liquidado.",
    adminResolveError: "Não foi possível liquidar. Verifique permissões admin.",
    adminFreezeTitle: "Congelar mercados abertos",
    adminFreezeBtn: "Congelar",
    adminFrozen: "Mercado congelado.",
    adminUnfrozen: "Mercado descongelado.",
    adminDraftTitle: "Rascunhos",
    adminOpenBtn: "Abrir mercado",
    adminOpened: "Mercado aberto para previsões.",
    adminFrozenList: "Congelados",
    adminUnfreezeBtn: "Descongelar",
    adminCreateTitle: "Novo mercado (rascunho)",
    adminCreateQuestion: "Pergunta",
    adminCreateQuestionPh: "Ex.: O fluxo na região ultrapassará a meta?",
    adminCreateDefaultQuestion: (region: string) =>
      `A métrica urbana em ${region} ultrapassará a meta no prazo?`,
    adminCreateNeedRegion: "Selecione uma região.",
    adminCreateSuccess: "Mercado criado em rascunho.",
    adminCreateBtn: "Criar rascunho",
    adminOpsCron: "Motor pg_cron",
    adminOpsLastTick: "Último tick",
    adminOpsHealthy: "Ativo",
    adminOpsStale: "Atrasado ou com erro",
    adminOpsDisputes: "Mercados em disputa",
    adminOpsLedger: "Receita da casa (ledger)",
    adminOpsLedgerEntries: "lançamentos",
    adminClaimTitle: "Painel operador",
    adminClaimDesc:
      "Use o código de convite da equipe (uso único) ou sincronize após vincular e-mail na allowlist.",
    adminClaimPlaceholder: "Ex.: VIAX-OPS-2026",
    adminClaimBtn: "Ativar admin",
    adminClaimSyncEmail: "Sincronizar e-mail",
    adminClaimSuccess: "Acesso de operador ativado.",
    adminClaimError: "Não foi possível ativar. Verifique o código.",
    adminClaimNeedCode: "Informe o código de convite.",
    adminClaimNoAllowlist: "E-mail ainda não está na lista de operadores.",
    profileTitle: "Meu perfil",
    profileName: "Nome de exibição",
    profileHandle: "Usuário (handle)",
    profileHandleHint: "3–30 caracteres: letras minúsculas, números e _",
    profileCity: "Cidade",
    profileNeighborhood: "Bairro",
    profileSave: "Salvar perfil",
    profileSaved: "Perfil atualizado.",
    profileHandleTaken: "Esse handle já está em uso.",
    profileHandleInvalid: "Handle inválido. Use letras minúsculas, números e _.",
    themeTitle: "Aparência",
    themeDark: "Tema escuro",
    themeLight: "Tema claro",
    themeDarkDesc: "Interface otimizada para ambientes com pouca luz.",
    themeLightDesc: "Alto contraste para uso diurno e telas externas.",
  },

  markets: {
    metaDescription: "Mercados ao vivo sobre trânsito e cidade na ViaX.",
    detailMeta:
      "Veja chances ao vivo, previsões da comunidade e a previsão da UrbanMind AI neste mercado.",
    sortEdge: "Com dica da IA",
    sortTrend: "Em alta",
    sortClosing: "Encerrando",
    poolTotal: "Volume no mercado",
    prizeTotal: "Prêmio total",
    tabBook: "Previsões",
    bookPressure: "Força das previsões",
    candlesNote: "Histórico (baseado nas chances)",
    participants: "participantes",
    tabAudit: "Auditoria",
    auditLoading: "Carregando trilha de resolução…",
    auditEmpty: "Nenhum registro de resolução ainda.",
    auditResolutions: "Resoluções",
    auditSnapshots: "Leituras do oráculo",
    auditNoSnapshots: "Sem snapshots na janela.",
    auditLedger: "Taxa da plataforma (ledger)",
    auditRaw: "Valor medido",
    closingSoon: (mins: number) => `Últimos ${Math.ceil(mins)} min — previsões encerram em breve!`,
    communityTab: "Comunidade",
    urbanTab: "Urbanos",
    transitoTab: "Trânsito",
    futebolTab: "Futebol",
    outrosTab: "Outros",
    segmentTransito: "Previsões sobre trânsito, fluxo e mobilidade urbana em tempo real.",
    segmentFutebol: "Mercados 1X2 aprovados pela equipe ViaX — vitória, empate ou visitante.",
    segmentOutros: "Mercados criados pela comunidade — publique ou participe de previsões Sim/Não.",
    marketNotFoundBanner:
      "Este mercado não está mais disponível. Confira os mercados ao vivo abaixo.",
  },

  community: {
    createTitle: "Criar previsão",
    createSubtitle: "Monte um mercado Sim/Não e convide amigos ou publique para todos.",
    questionLabel: "Pergunta",
    questionPlaceholder: "Ex.: O time X vence o clássico no domingo?",
    endsLabel: "Encerra em",
    endsDateLabel: "Data",
    endsTimeLabel: "Horário",
    endsTimezoneHint: "Horário de Brasília (UTC−3).",
    endsTooSoon: "O encerramento deve ser pelo menos 1 hora no futuro.",
    endsTooFar: "O encerramento não pode passar de 90 dias.",
    endsInvalid: "Informe data e horário válidos.",
    coverLabel: "Capa (opcional)",
    coverHint: "JPEG, PNG ou WebP — até 2 MB.",
    coverUploadError: "Não foi possível enviar a imagem. Tente outra foto.",
    coverTypeError: "Use JPEG, PNG ou WebP.",
    coverSizeError: "A imagem deve ter no máximo 2 MB.",
    visibilityLabel: "Quem pode participar",
    visibilityPublic: "Público — aparece na aba Outros",
    visibilityPrivate: "Privado — só quem tiver o link",
    creatorNote:
      "Você define o resultado após o prazo. Não é possível apostar no próprio mercado. Exige cadastro formal.",
    createCta: "Publicar mercado",
    createSuccessPublic: "Mercado publicado!",
    createSuccessPrivate: "Mercado privado criado — compartilhe o link.",
    shareTitle: "Link do mercado privado",
    shareDesc: "Envie este link para quem pode apostar. Guarde-o — não listamos mercados privados.",
    copyLink: "Copiar link",
    linkCopied: "Link copiado.",
    openMarket: "Abrir mercado",
    backToList: "Voltar aos mercados",
    listTitle: "Previsões da comunidade",
    listSubtitle: "Mercados criados por traders — resolução pelo autor.",
    createLink: "Criar previsão",
    myMarkets: "Meus mercados",
    privateBadge: "Privado",
    communityBadge: "Comunidade",
    accessDenied: "Este mercado é privado. Peça o link completo a quem criou.",
    accessJoining: "Validando convite…",
    creatorPanelTitle: "Você é o criador",
    creatorWaitEnd: "Após o prazo, escolha Sim ou Não para liquidar o mercado.",
    creatorResolveHint: "Defina o resultado oficial para pagar quem acertou.",
    confirmResolve: (side: "YES" | "NO") =>
      `Confirmar resultado: ${side === "YES" ? "SIM" : "NÃO"}`,
    resolveSuccess: "Mercado liquidado.",
    voidCta: "Cancelar e reembolsar todos",
    voidConfirm: "Cancelar este mercado e devolver as apostas?",
    voidSuccess: "Mercado cancelado — saldos reembolsados.",
    poolNote: "Pool parimutuel — 90% para vencedores após taxa da plataforma.",
    reportCta: "Denunciar",
    reportTitle: "Denunciar mercado",
    reportPlaceholder: "Descreva o problema (mín. 5 caracteres)",
    reportReasonMin: "Informe pelo menos 5 caracteres.",
    reportSubmit: "Enviar denúncia",
    reportSuccess: "Denúncia registrada. Nossa equipe vai analisar.",
    reportAlready: "Você já denunciou este mercado.",
    adminCommunityTitle: "Mercados da comunidade",
    adminReportsTitle: "Denúncias pendentes",
    adminVoidCommunity: "Anular mercado",
  },

  marketCard: {
    prizeTotal: "Prêmio total",
    traders: "participantes",
  },

  ranking: {
    followingSort: "Quem você segue, ordenado pelo retorno da última semana.",
    defaultSort: "Os melhores previsores da comunidade.",
    precision: "Precisão",
    return: "Retorno",
  },

  urbanmind: {
    iaPrecisionChart: "Precisão da IA e da comunidade · 30 dias",
    betWithIa: "Prever seguindo a IA",
    edgeVsPool: "Diferença IA × previsões",
  },

  feed: {
    metaDescription: "Análises, alertas e previsões de quem prevê o trânsito da cidade.",
    betYes: "Prever SIM",
    betNo: "Prever NÃO",
    prize: "Prêmio",
  },

  root: {
    backToApp: "Voltar ao app",
    errorTitle: "Algo deu errado",
    errorDesc: "Não foi possível carregar esta página. Tente de novo.",
    metaDescription:
      "Previsões sobre trânsito e cidade em tempo real. Ranking da comunidade e previsão da UrbanMind AI.",
  },

  sidebar: {
    brand: "ViaX",
  },

  errors: {
    generic: "Algo deu errado",
    genericDesc: "Tente de novo ou volte ao início.",
    marketStuck: "Não foi possível carregar este mercado",
    backToApp: "Voltar ao app",
    rateLimited: "Muitas tentativas. Aguarde um momento e tente de novo.",
    unauthorized: "Sessão expirada. Faça login novamente.",
    registrationRequired: "Conclua o cadastro para continuar.",
    insufficientBalance: "Saldo insuficiente para esta operação.",
    followFailed: "Não foi possível atualizar o acompanhamento.",
    depositPollFailed: "Não conseguimos confirmar o pagamento. Verifique em Histórico.",
    loadFailed: "Não foi possível carregar os dados.",
  },

  command: {
    placeholder: "Buscar mercados, páginas, traders… (⌘K)",
    empty: "Nenhum resultado.",
    routes: "Páginas",
    markets: "Mercados",
  },

  notifications: {
    metaDescription: "Alertas de mercados, ganhos e novidades na ViaX.",
    resolveDesc: "Confira os ganhos na carteira.",
  },

  empty: {
    noFavorites: "Nenhum favorito ainda.",
    markets: {
      title: "Nenhum mercado encontrado",
      description: "Ajuste os filtros ou explore todos os mercados abertos.",
      cta: "Ver todos os mercados",
    },
    favorites: {
      title: "Nenhum favorito ainda",
      description: "Toque na ★ em qualquer card de mercado para salvar aqui.",
      cta: "Explorar mercados",
    },
    notifications: {
      title: "Nenhuma notificação",
      description: "Quando um mercado fechar ou você ganhar, o alerta aparece aqui.",
      cta: "Ver mercados",
    },
    feed: {
      title: "Feed vazio",
      description: "Seja o primeiro a publicar ou acompanhe os mercados em alta.",
      cta: "Ver mercados",
    },
    ranking: {
      title: "Ranking ainda sem dados",
      description: "Participe de mercados para aparecer no placar da comunidade.",
      cta: "Fazer uma previsão",
    },
    live: {
      regions: {
        title: "Sem regiões no mapa",
        description: "Aguarde a sincronização ou abra o painel de operações.",
        cta: "Ver mercados",
      },
      markets: {
        title: "Nenhum mercado ativo",
        description: "Novos mercados urbanos aparecem aqui quando abrirem.",
        cta: "Lista de mercados",
      },
    },
    positions: {
      title: "Nenhuma previsão aberta",
      description: "Escolha SIM ou NÃO em um mercado ao vivo para começar.",
      cta: "Explorar mercados",
    },
    wallet: {
      title: "Sem movimentações",
      description: "Depósitos Pix e ganhos de mercados resolvidos aparecem aqui.",
      cta: "Ver mercados",
    },
    dashboardFeed: {
      title: "Nenhum post no feed",
      description: "A comunidade ainda não publicou — confira os mercados ao vivo.",
      cta: "Abrir feed",
    },
    profileFavorites: {
      title: "Sem favoritos",
      description: "Marque mercados com ★ para acompanhar de perto.",
      cta: "Ir aos mercados",
    },
    traders: {
      title: "Sem histórico público",
      description: "Este trader ainda não tem resultados resolvidos visíveis.",
      cta: "Ver ranking",
    },
  },

  retention: {
    dailyPulseTitle: "Pulso diário da cidade",
    dailyPulseCta: "30 segundos para ver como está São Paulo hoje — e manter sua sequência.",
    dailyPulseDone: "Check-in feito. O mapa e os mercados te esperam.",
    checkInBtn: "Fazer check-in",
    checkingIn: "Registrando…",
    checkInSuccess: (xp: number) => `+${xp} XP · sequência atualizada`,
    alreadyCheckedIn: "Você já fez o check-in hoje.",
    openLiveMap: "Ver mapa ao vivo",
    streakDays: (n: number) => (n === 1 ? "1 dia de sequência" : `${n} dias de sequência`),
    streakAtRisk: (n: number) => `Sua sequência de ${n} dias pode zerar hoje — faça o check-in.`,
    useFreeze: "Congelar 1 dia",
    freezeUsed: "Sequência protegida por hoje.",
    freezeUnavailable: "Sem congelamentos disponíveis.",
    urbanmindDigestTitle: "UrbanMind · seu treinador urbano",
    vsAiRate: (w: number, t: number) =>
      `Você vs IA: ${w} acertos em ${t} previsões contra a máquina`,
    openUrbanmind: "Abrir UrbanMind",
    weeklyChallengeTitle: "Desafio da semana",
    precisionReportTitle: "Seu relatório de precisão",
    allTimeAccuracy: "Precisão geral",
    weekAccuracy: "Últimos 7 dias",
    precisionReportHint: "Foco em melhorar 2 pontos percentuais — sem pressão de ranking.",
    achievementUnlocked: (name: string) => `Conquista desbloqueada: ${name}`,
    dailyMission: "Missão do dia",
    dailyMissionDesc: "Mercado sugerido na sua região",
    emailBonusToast: "+500 XP por proteger sua conta com e-mail.",
    pushDigestLabel: "Resumo matinal (navegador)",
    pushDigestDesc: "Lembrete opcional para check-in e pulso urbano — sem spam.",
    streakMultiplierLabel: (x: number) => `Multiplicador ${x}x ativo`,
    recoveryModeActive: "Modo Recuperação: XP em dobro",
    buyFreezeLabel: "Comprar freeze (200 XP)",
    weeklyReportTitle: "Sua Semana em SP",
    missionComplete: (label: string, xp: number) => `✅ ${label} — +${xp} XP`,
    weeklyReportKeepPredicting: "Continue prevendo aí — você conhece o terreno.",
    weeklyReportExplore: "Preveja em mais mercados para descobrir sua região forte!",
  },

  leagues: {
    title: "Ligas Privadas",
    subtitle: "Crie grupos com amigos e compita em ranking privado.",
    create: "Criar liga",
    join: "Entrar com código",
    inviteCode: "Código de convite",
    memberCount: (n: number) => `${n} membro${n !== 1 ? "s" : ""}`,
    leaveLeague: "Sair da liga",
    noLeagues: "Você ainda não está em nenhuma liga.",
    createFirst: "Crie a sua ou entre com o código de um amigo.",
  },

  poll: {
    title: "Poll do Dia",
    xpReward: "+10 XP por votar",
    voted: (choice: string) => `Você votou: ${choice}`,
    totalVotes: (n: number) => `${n} voto${n !== 1 ? "s" : ""}`,
  },

  events: {
    sectionTitle: "Eventos sazonais",
    liveNow: "Ao vivo",
    viewOnDashboard: "Ver no dashboard →",
    dismiss: "Dispensar evento",
    loadError: "Não foi possível carregar os eventos.",
    endsIn: (when: string) => `Encerra ${when}`,
    xpBoost: (n: number) => `+${n} XP bônus`,
  },

  depositFunnel: {
    bannerTitle: "Deposite via Pix para apostar",
    bannerBody: "Cadastro concluído — adicione saldo em segundos e entre nas previsões ao vivo.",
    bannerCta: "Depositar agora",
    insufficientCta: "Depositar via Pix",
    postSignupToast: "Conta pronta! Deposite para começar a prever.",
    rankingCta: "Cadastre-se para subir no ranking",
    referredBy: "Indicado por",
  },

  casino: {
    wheelTitle: "Roleta diária",
    wheelDesc: "1 giro grátis por dia. Depósito de 100 BRL+ libera giro bônus em 24h.",
    spinFree: "Girar grátis",
    alreadySpunToday: "Você já girou hoje",
    spinWin: (label: string) => `Resultado: ${label}`,
    nearMissJackpot: "Quase no jackpot! Deposite 100 BRL e ganhe +1 giro.",
    depositBonusCta: "Depositar e ganhar giro",
    bonusSpinGranted: "Giro bônus liberado!",
    nearMissTitle: "Quase!",
    nearMissBody: (gap: number) =>
      `Você ficou a cerca de ${gap}% do equilíbrio do prêmio — na próxima pode virar.`,
    nearMissStake: (stake: string) => `Participação: ${stake}`,
    tryAnotherMarket: "Tentar outro mercado",
    reloadAndContinue: (amt: string) => `Recarregar ${amt} e continuar`,
    lowBalanceBanner: (bal: string) => `Saldo baixo (${bal}) — recarregue em 1 toque`,
    oneTapReload: (amt: string) => `Recarregar ${amt}`,
    depositSuccess: (bal: string) => `Saldo atualizado: ${bal}`,
    maxQuick: (amt: number) => `Máx. rápido · ${amt} BRL`,
    impulseDepositTitle: "Recarga rápida",
    impulseDepositHint: "Valores pré-definidos — máx. 3 recargas por hora.",
    hotZoneLabel: "Zona quente",
  },

  responsiblePlay: {
    disclaimerShort:
      "Recargas rápidas da roleta usam créditos promocionais — depósitos reais são via Pix na carteira.",
    understood: "Entendi",
    settingsTitle: "Modo intenso (roleta e recargas)",
    settingsDesc:
      "Desligue para ocultar roleta, near-miss e banners de recarga. Check-in e hábitos saudáveis continuam ativos.",
    intenseOn: "Modo intenso ativo",
    intenseOff: "Modo tranquilo (sem cassino)",
    optOutSaved: "Preferência salva.",
  },

  partner: {
    title: "Creator Hub",
    subtitle: "Analista urbano · revenue share",
    backToApp: "Voltar ao app",
    nav: {
      overview: "Overview",
      revenue: "Receita",
      invites: "Convites",
      performance: "Performance",
      leaderboard: "Leaderboard",
      campaigns: "Campanhas",
      creatives: "Criativos",
      analytics: "Analytics",
      subAffiliates: "Sub-creators",
      payouts: "Pagamentos",
    },
    applyTitle: "Programa Creator ViaX",
    applyDesc:
      "Monetize sua audiência com revenue share sobre o rake — estilo trading network, não marketing multinível.",
    applyCta: "Enviar candidatura",
    applyPending: "Candidatura em análise. Avisaremos quando aprovado.",
    pendingPageTitle: "Candidatura em análise",
    pendingPageDesc:
      "Nossa equipe está revisando seu perfil de creator. Você receberá acesso ao hub assim que for aprovado.",
    pendingPageLink: "Ver status da candidatura",
    pendingBackToSettings: "Voltar às configurações",
    portalCta: "Abrir Creator Hub",
    stats: {
      revenue: "Receita total",
      referrals: "Traders indicados",
      volume: "Volume gerado",
      conversion: "Conversão",
      commissionHint: "do rake da plataforma",
      cpaHint: "CPA · qualifica com depósito de",
    },
    liveFeed: "Feed ao vivo",
    expertPage: "Página creator",
    verified: "Analista verificado",
    followAnalyst: "Seguir analista",
    favoriteMarkets: "Mercados favoritos",
    creativeGenerate: "Gerar criativo automático",
    creativeDownload: "Baixar PNG",
    payoutRequest: "Solicitar saque",
    payoutSimulateCta: "Simular saque",
    simulatedPayout:
      "Saques de creator ainda são simulados. O saldo é debitado apenas para testes — nenhum Pix real é enviado.",
    payoutSimulatedTitle: "Saques ainda não são reais",
    payoutSimulatedNote:
      "Quando Pix estiver habilitado, você receberá e-mail e verá status “Pendente” no histórico.",
    payoutSimulatedSuccess: (balance: string) => `Saque simulado registrado · saldo ${balance}`,
    payoutPendingSuccess: (balance: string) => `Saque Pix solicitado · saldo ${balance}`,
    payoutRealTitle: "Saques via Pix",
    payoutRealNote: "Transferências reais podem levar até 1 dia útil após aprovação.",
    payoutAmountSimulated: "Valor (simulação)",
    payoutAmountReal: "Valor (Pix)",
    payoutStatusSimulated: "Simulado",
    payoutStatusPending: "Pendente",
    payoutStatusCompleted: "Pago",
    subInvite: "Código para sub-creators (máx. 2 níveis)",
    missionsTitle: "Missões da semana",
    predictions24h: "Previsões 24h (indicados)",
    inviteBetColumn: "Previsão",
    creativeYesPct: (pct: string) => `${pct} prevêem SIM`,
  },

  admin: {
    title: "Control Center",
    subtitle: "Trading & Urban Intelligence",
    backToApp: "Voltar ao app",
    accessDenied: "Acesso restrito a operadores.",
    partnerBadge: "Afiliado",
    nav: {
      overview: "Overview",
      markets: "Mercados",
      settlement: "Liquidação",
      intelligence: "IA & Dados",
      sources: "Fontes",
      finance: "Financeiro",
      users: "Usuários",
      risk: "Risco",
      system: "Sistema",
      simulator: "Simulador",
      partners: "Creators",
      events: "Eventos",
      football: "Futebol",
    },
    football: {
      title: "Futebol · API-Sports",
      subtitle: "Sincronização automática · publicação manual",
      tabPending: "Pendentes",
      tabDrafts: "Rascunhos",
      tabPublished: "Publicados",
      tabSettings: "Configuração",
      emptyPending: "Nenhum jogo aguardando aprovação.",
      emptyDrafts: "Nenhum mercado em rascunho.",
      emptyPublished: "Nenhum mercado publicado ou liquidado.",
      void: "Anular mercado",
      voidDone: "Mercado anulado — apostas reembolsadas.",
      regulationHint:
        "Resultado: placar final reportado pela API (FT/AET). Com football_regulation=90min no banco, o sync usa o placar do intervalo regulamentar quando disponível.",
      approve: "Aprovar",
      reject: "Rejeitar",
      publish: "Publicar",
      approved: "Jogo aprovado — mercado em rascunho.",
      rejected: "Jogo rejeitado.",
      published: "Mercado publicado — apostas abertas.",
      enabledLabel: "Ativo",
      leaguesLabel: "IDs de ligas (API-Sports)",
      settingsHint: "IDs numéricos da API-Sports (ex.: 71 = Brasileirão).",
      leaguesHint: "Separados por vírgula.",
      syncDaysLabel: "Dias à frente no sync",
      closeMinutesLabel: "Minutos antes do apito para fechar apostas",
      saveSettings: "Salvar configuração",
      settingsSaved: "Configuração de futebol salva.",
      syncNow: "Sincronizar API agora",
      resolveNow: "Liquidar jogos finalizados",
      syncDone: "Sync concluído — veja a fila Pendentes.",
      resolveDone: "Resolução executada.",
      syncFailed: "Falha no sync (verifique API_FOOTBALL_KEY no servidor).",
      resolveFailed: "Falha na resolução.",
      cronHint: "Produção: cron Cloudflare */30 sync e */5 resolve (wrangler.jsonc).",
      yes: "Sim",
      no: "Não",
    },
    events: {
      title: "Hub de eventos",
      subtitle: "Sazonais · enquetes · afiliados · atalhos operacionais",
      tabOverview: "Overview",
      tabSeasonal: "Sazonais",
      tabPolls: "Enquetes",
      tabAffiliates: "Afiliados",
      seasonalActive: "Ativos",
      seasonalUpcoming: "Agendados",
      seasonalEnded: "Encerrados",
      pollsToday: "Enquete hoje",
      partnerEvents24h: "Eventos afiliados (24h)",
      marketsLive: "Mercados ao vivo",
      marketsDispute: "Em disputa",
      marketsDraft: "Rascunhos",
      footballPending: "Jogos pendentes",
      communityReports: "Denúncias pendentes",
      goMarkets: "Ir para Mercados",
      goFootball: "Ir para Futebol",
      goPartners: "Ir para Creators",
      createEvent: "Criar evento",
      editEvent: "Editar",
      deleteEvent: "Excluir",
      eventSaved: "Evento salvo.",
      eventDeleted: "Evento excluído.",
      pollSaved: "Enquete salva.",
      pollDeleted: "Enquete excluída.",
      partnerEventDeleted: "Evento removido do feed.",
      statusActive: "Ativo",
      statusUpcoming: "Agendado",
      statusEnded: "Encerrado",
      emptySeasonal: "Nenhum evento sazonal.",
      emptyPolls: "Nenhuma enquete cadastrada.",
      emptyPartnerEvents: "Nenhum evento de afiliado.",
      name: "Nome",
      slug: "Slug",
      description: "Descrição",
      startsAt: "Início",
      endsAt: "Fim",
      badgeIcon: "Ícone",
      xpBoost: "XP bônus",
      save: "Salvar",
      question: "Pergunta",
      pollDate: "Data",
      createPoll: "Criar enquete",
      votesYes: "Sim",
      votesNo: "Não",
      filterPartner: "Filtrar por @handle (opcional)",
      applyFilter: "Filtrar",
      clearFilter: "Limpar",
    },
    partners: {
      title: "Fila Creator",
      approve: "Aprovar",
      reject: "Rejeitar",
      empty: "Nenhuma candidatura pendente.",
      activeTitle: "Afiliados ativos",
      activeEmpty: "Nenhum afiliado ativo.",
      revenueShare: "Comissão (0–1)",
      cpaAmount: "CPA (R$)",
      cpaUseDefault: "Padrão global",
      saveTerms: "Salvar termos",
      termsSaved: "Termos atualizados.",
      referrals: "Indicados",
    },
    metrics: {
      volumeToday: "Volume hoje",
      revenueToday: "Receita (10%)",
      activeMarkets: "Mercados ativos",
      dau: "Usuários ativos (24h)",
      openPools: "Pools abertos",
      disputes: "Em disputa",
      cronStatus: "Motor cron",
      liveFeed: "Feed ao vivo",
    },
    markets: {
      title: "Prediction Engine",
      create: "Criar mercado",
      forceClose: "Forçar fechamento",
      tableStatus: "Status",
      tableVolume: "Volume",
    },
    settlement: {
      title: "Settlement Engine",
      poolTotal: "Pool total",
      houseFee: "Taxa plataforma",
      prize: "Prêmio líquido",
      reprocess: "Reprocessar oráculo",
      execute: "Liquidar",
    },
    simulator: {
      title: "Simulador urbano",
      rush: "Horário de pico",
      rain: "Chuva forte",
      preview: "Preview regiões",
      applyNote: "Cenários afetam apenas simulação local até integração completa.",
      yourStake: "Sua participação (BRL)",
    },
    sources: {
      title: "Fontes de dados",
      synthetic: "Regiões (simulador)",
      cameras: "Câmeras",
      addCamera: "Adicionar câmera",
      detectionOk: "Detecção ativa",
      detectionPending: "Aguardando worker",
      lastCount: "Última contagem",
      visionWorkerTitle: "Vision worker",
      visionWorkerHealthy: "Ativo",
      visionWorkerStale: "Atenção",
      visionWorkerNoRuns: "Nenhuma execução registrada. Verifique GitHub Actions ou Docker.",
      visionWorkerLastRun: (at: string, source: string, ok: number, total: number) =>
        `Último ciclo: ${at} · origem ${source} · ${ok}/${total} câmeras OK`,
    },
    intelligence: {
      yoloDemo: "Rodar inferência demo (YOLO)",
      yoloDemoDone: "Demo: 42 veículos · 18 pedestres (simulado)",
      yoloNote: "Modelo real exige worker GPU; este botão só valida o fluxo ops.",
    },
    users: {
      freeze: "Congelar",
      unfreeze: "Descongelar",
      betLimit: "Limite de participação",
    },
    risk: {
      title: "Risco & fraude",
      empty: "Nenhum alerta no momento.",
    },
    system: {
      title: "DNA do produto",
      save: "Salvar",
      casinoEnabled: "Mecânicas estilo cassino",
      casinoEnabledHint: "Roleta, near-miss e depósito impulsivo no app.",
      impulseMaxHour: "Máx. recargas rápidas / hora",
      maxStake: "Participação máxima (BRL)",
      defaultCpa: "CPA padrão (R$)",
      cpaMinDeposit: "Depósito mínimo para CPA (R$)",
    },
    finance: {
      openPredictions: "Previsões em jogo",
    },
    overview: {
      noPredictions24h: "Sem previsões nas últimas 24h.",
    },
  },

  social: {
    recentPredictionsLoading: "Carregando previsões recentes…",
    noRecentPredictions: "Nenhuma previsão recente neste mercado.",
    predictionsAccelerating: "Previsões acelerando",
    recentPredictions: "Previsões recentes",
    predictionsLabel: "Previsões",
    traderPredictions: (n: number) => `${n} previsões`,
    divisionKeepPredicting: "Continue prevendo para manter e avançar sua divisão.",
    continuePredicting: "Continuar prevendo",
  },

  push: {
    predictBeforeClose: (n: number) =>
      `${n} mercados de congestionamento abertos agora. Preveja antes de fechar.`,
  },

  cameras: {
    liveTitle: "Ao vivo",
    liveSubtitle: "Stream da região · UrbanMind",
    offline: "Câmera offline",
    noSignal: "Sem sinal ao vivo nesta região",
    privacyNote: "Imagem de tráfego público. Evite identificar pessoas.",
    previewAlt: "Preview da câmera",
    openExternal: "Abrir stream externo",
    rtspHint: "RTSP/RTMP exige gateway HLS — use URL .m3u8 HTTPS no cadastro.",
    hlsUnsupported: "HLS não suportado neste navegador.",
    streamError: "Não foi possível carregar o stream.",
    invalidUrl: "URL inválida. Use HTTPS com .m3u8, snapshot ou YouTube.",
    mixedContent: "Stream HTTP não reproduz no app HTTPS. Use URL HTTPS ou abra externamente.",
    corsHint: "Se o vídeo não carregar, pode ser CORS do provedor do stream.",
    lastReading: "Última leitura",
    staleDetection: "Detecção sem atualização há mais de 10 min",
  },
} as const;

export function betSideLabel(side: Side): "SIM" | "NÃO" {
  return side === "YES" ? "SIM" : "NÃO";
}

export function toastBetSuccess(side: Side, stake: string, payout: string) {
  return {
    title: `Previsão ${betSideLabel(side)} · ${stake}`,
    description: `${copy.bet.potentialWin}: ${payout}`,
  };
}

export function iaEdgeLabel(side: Side, edgePp: number): string {
  if (Math.abs(edgePp) < 1) return copy.ia.neutral(side);
  return copy.ia.favors(side);
}
