/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PartnerRouteRouteImport } from './routes/partner/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as MarketsIndexRouteImport } from './routes/markets/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PartnerSubAffiliatesRouteImport } from './routes/partner/sub-affiliates'
import { Route as PartnerRevenueRouteImport } from './routes/partner/revenue'
import { Route as PartnerPerformanceRouteImport } from './routes/partner/performance'
import { Route as PartnerPendingRouteImport } from './routes/partner/pending'
import { Route as PartnerPayoutsRouteImport } from './routes/partner/payouts'
import { Route as PartnerLeaderboardRouteImport } from './routes/partner/leaderboard'
import { Route as PartnerInvitesRouteImport } from './routes/partner/invites'
import { Route as PartnerCreativesRouteImport } from './routes/partner/creatives'
import { Route as PartnerCampaignsRouteImport } from './routes/partner/campaigns'
import { Route as PartnerAnalyticsRouteImport } from './routes/partner/analytics'
import { Route as MarketsMarketIdRouteImport } from './routes/markets/$marketId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AdminSimulatorRouteImport } from './routes/admin/simulator'
import { Route as AdminSettlementRouteImport } from './routes/admin/settlement'
import { Route as AdminRiskRouteImport } from './routes/admin/risk'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminMarketsRouteImport } from './routes/admin/markets'
import { Route as AdminIntelligenceRouteImport } from './routes/admin/intelligence'
import { Route as AdminFootballRouteImport } from './routes/admin/football'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppUrbanmindRouteImport } from './routes/_app/urbanmind'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPositionsRouteImport } from './routes/_app/positions'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppLeaguesRouteImport } from './routes/_app/leagues'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFootballIndexRouteImport } from './routes/_app/football/index'
import { Route as ApiWebhooksSyncpayRouteImport } from './routes/api/webhooks/syncpay'
import { Route as ApiCronFootballSyncRouteImport } from './routes/api/cron/football-sync'
import { Route as ApiCronFootballResolveRouteImport } from './routes/api/cron/football-resolve'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppMarketsCreateRouteImport } from './routes/_app/markets.create'
import { Route as AppFootballMarketIdRouteImport } from './routes/_app/football/$marketId'
import { Route as AppFeedPostIdRouteImport } from './routes/_app/feed.$postId'
import { Route as ApiPublicSnapshotProxySplatRouteImport } from './routes/api/public/snapshot-proxy/$'
import { Route as ApiPublicHlsProxySplatRouteImport } from './routes/api/public/hls-proxy/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRouteRoute = PartnerRouteRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSubAffiliatesRoute = PartnerSubAffiliatesRouteImport.update({
  id: '/sub-affiliates',
  path: '/sub-affiliates',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerRevenueRoute = PartnerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerPerformanceRoute = PartnerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerPendingRoute = PartnerPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerPayoutsRoute = PartnerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerLeaderboardRoute = PartnerLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerInvitesRoute = PartnerInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerCreativesRoute = PartnerCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerCampaignsRoute = PartnerCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerAnalyticsRoute = PartnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => MarketsRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSimulatorRoute = AdminSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettlementRoute = AdminSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFootballRoute = AdminFootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanmindRoute = AppUrbanmindRouteImport.update({
  id: '/urbanmind',
  path: '/urbanmind',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesRoute = AppLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFootballIndexRoute = AppFootballIndexRouteImport.update({
  id: '/football/',
  path: '/football/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksSyncpayRoute = ApiWebhooksSyncpayRouteImport.update({
  id: '/api/webhooks/syncpay',
  path: '/api/webhooks/syncpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFootballSyncRoute = ApiCronFootballSyncRouteImport.update({
  id: '/api/cron/football-sync',
  path: '/api/cron/football-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFootballResolveRoute = ApiCronFootballResolveRouteImport.update({
  id: '/api/cron/football-resolve',
  path: '/api/cron/football-resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppMarketsCreateRoute = AppMarketsCreateRouteImport.update({
  id: '/markets/create',
  path: '/markets/create',
  getParentRoute: () => AppRoute,
} as any)
const AppFootballMarketIdRoute = AppFootballMarketIdRouteImport.update({
  id: '/football/$marketId',
  path: '/football/$marketId',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedPostIdRoute = AppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppFeedRoute,
} as any)
const ApiPublicSnapshotProxySplatRoute =
  ApiPublicSnapshotProxySplatRouteImport.update({
    id: '/api/public/snapshot-proxy/$',
    path: '/api/public/snapshot-proxy/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHlsProxySplatRoute = ApiPublicHlsProxySplatRouteImport.update({
  id: '/api/public/hls-proxy/$',
  path: '/api/public/hls-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/partner': typeof PartnerRouteRouteWithChildren
  '/live': typeof LiveRoute
  '/markets': typeof MarketsRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/leagues': typeof AppLeaguesRoute
  '/notifications': typeof AppNotificationsRoute
  '/positions': typeof AppPositionsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/urbanmind': typeof AppUrbanmindRoute
  '/wallet': typeof AppWalletRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/football': typeof AdminFootballRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/creatives': typeof PartnerCreativesRoute
  '/partner/invites': typeof PartnerInvitesRoute
  '/partner/leaderboard': typeof PartnerLeaderboardRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/pending': typeof PartnerPendingRoute
  '/partner/performance': typeof PartnerPerformanceRoute
  '/partner/revenue': typeof PartnerRevenueRoute
  '/partner/sub-affiliates': typeof PartnerSubAffiliatesRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/football/$marketId': typeof AppFootballMarketIdRoute
  '/markets/create': typeof AppMarketsCreateRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/api/cron/football-resolve': typeof ApiCronFootballResolveRoute
  '/api/cron/football-sync': typeof ApiCronFootballSyncRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/football/': typeof AppFootballIndexRoute
  '/api/public/hls-proxy/$': typeof ApiPublicHlsProxySplatRoute
  '/api/public/snapshot-proxy/$': typeof ApiPublicSnapshotProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/live': typeof LiveRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/leagues': typeof AppLeaguesRoute
  '/notifications': typeof AppNotificationsRoute
  '/positions': typeof AppPositionsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/urbanmind': typeof AppUrbanmindRoute
  '/wallet': typeof AppWalletRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/football': typeof AdminFootballRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/creatives': typeof PartnerCreativesRoute
  '/partner/invites': typeof PartnerInvitesRoute
  '/partner/leaderboard': typeof PartnerLeaderboardRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/pending': typeof PartnerPendingRoute
  '/partner/performance': typeof PartnerPerformanceRoute
  '/partner/revenue': typeof PartnerRevenueRoute
  '/partner/sub-affiliates': typeof PartnerSubAffiliatesRoute
  '/r/$slug': typeof RSlugRoute
  '/admin': typeof AdminIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/football/$marketId': typeof AppFootballMarketIdRoute
  '/markets/create': typeof AppMarketsCreateRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/api/cron/football-resolve': typeof ApiCronFootballResolveRoute
  '/api/cron/football-sync': typeof ApiCronFootballSyncRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/football': typeof AppFootballIndexRoute
  '/api/public/hls-proxy/$': typeof ApiPublicHlsProxySplatRoute
  '/api/public/snapshot-proxy/$': typeof ApiPublicSnapshotProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/partner': typeof PartnerRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/live': typeof LiveRoute
  '/markets': typeof MarketsRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/leagues': typeof AppLeaguesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/urbanmind': typeof AppUrbanmindRoute
  '/_app/wallet': typeof AppWalletRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/football': typeof AdminFootballRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/creatives': typeof PartnerCreativesRoute
  '/partner/invites': typeof PartnerInvitesRoute
  '/partner/leaderboard': typeof PartnerLeaderboardRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/pending': typeof PartnerPendingRoute
  '/partner/performance': typeof PartnerPerformanceRoute
  '/partner/revenue': typeof PartnerRevenueRoute
  '/partner/sub-affiliates': typeof PartnerSubAffiliatesRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/_app/feed/$postId': typeof AppFeedPostIdRoute
  '/_app/football/$marketId': typeof AppFootballMarketIdRoute
  '/_app/markets/create': typeof AppMarketsCreateRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/api/cron/football-resolve': typeof ApiCronFootballResolveRoute
  '/api/cron/football-sync': typeof ApiCronFootballSyncRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/_app/football/': typeof AppFootballIndexRoute
  '/api/public/hls-proxy/$': typeof ApiPublicHlsProxySplatRoute
  '/api/public/snapshot-proxy/$': typeof ApiPublicSnapshotProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/partner'
    | '/live'
    | '/markets'
    | '/ranking'
    | '/sitemap.xml'
    | '/dashboard'
    | '/feed'
    | '/leagues'
    | '/notifications'
    | '/positions'
    | '/profile'
    | '/settings'
    | '/urbanmind'
    | '/wallet'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/football'
    | '/admin/intelligence'
    | '/admin/markets'
    | '/admin/partners'
    | '/admin/risk'
    | '/admin/settlement'
    | '/admin/simulator'
    | '/admin/sources'
    | '/admin/system'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/markets/$marketId'
    | '/partner/analytics'
    | '/partner/campaigns'
    | '/partner/creatives'
    | '/partner/invites'
    | '/partner/leaderboard'
    | '/partner/payouts'
    | '/partner/pending'
    | '/partner/performance'
    | '/partner/revenue'
    | '/partner/sub-affiliates'
    | '/r/$slug'
    | '/admin/'
    | '/markets/'
    | '/partner/'
    | '/feed/$postId'
    | '/football/$marketId'
    | '/markets/create'
    | '/profile/$userId'
    | '/api/cron/football-resolve'
    | '/api/cron/football-sync'
    | '/api/webhooks/syncpay'
    | '/football/'
    | '/api/public/hls-proxy/$'
    | '/api/public/snapshot-proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/live'
    | '/ranking'
    | '/sitemap.xml'
    | '/dashboard'
    | '/feed'
    | '/leagues'
    | '/notifications'
    | '/positions'
    | '/profile'
    | '/settings'
    | '/urbanmind'
    | '/wallet'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/football'
    | '/admin/intelligence'
    | '/admin/markets'
    | '/admin/partners'
    | '/admin/risk'
    | '/admin/settlement'
    | '/admin/simulator'
    | '/admin/sources'
    | '/admin/system'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/markets/$marketId'
    | '/partner/analytics'
    | '/partner/campaigns'
    | '/partner/creatives'
    | '/partner/invites'
    | '/partner/leaderboard'
    | '/partner/payouts'
    | '/partner/pending'
    | '/partner/performance'
    | '/partner/revenue'
    | '/partner/sub-affiliates'
    | '/r/$slug'
    | '/admin'
    | '/markets'
    | '/partner'
    | '/feed/$postId'
    | '/football/$marketId'
    | '/markets/create'
    | '/profile/$userId'
    | '/api/cron/football-resolve'
    | '/api/cron/football-sync'
    | '/api/webhooks/syncpay'
    | '/football'
    | '/api/public/hls-proxy/$'
    | '/api/public/snapshot-proxy/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/partner'
    | '/_app'
    | '/live'
    | '/markets'
    | '/ranking'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/leagues'
    | '/_app/notifications'
    | '/_app/positions'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/urbanmind'
    | '/_app/wallet'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/football'
    | '/admin/intelligence'
    | '/admin/markets'
    | '/admin/partners'
    | '/admin/risk'
    | '/admin/settlement'
    | '/admin/simulator'
    | '/admin/sources'
    | '/admin/system'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/markets/$marketId'
    | '/partner/analytics'
    | '/partner/campaigns'
    | '/partner/creatives'
    | '/partner/invites'
    | '/partner/leaderboard'
    | '/partner/payouts'
    | '/partner/pending'
    | '/partner/performance'
    | '/partner/revenue'
    | '/partner/sub-affiliates'
    | '/r/$slug'
    | '/admin/'
    | '/markets/'
    | '/partner/'
    | '/_app/feed/$postId'
    | '/_app/football/$marketId'
    | '/_app/markets/create'
    | '/_app/profile/$userId'
    | '/api/cron/football-resolve'
    | '/api/cron/football-sync'
    | '/api/webhooks/syncpay'
    | '/_app/football/'
    | '/api/public/hls-proxy/$'
    | '/api/public/snapshot-proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PartnerRouteRoute: typeof PartnerRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LiveRoute: typeof LiveRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  RankingRoute: typeof RankingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RSlugRoute: typeof RSlugRoute
  ApiCronFootballResolveRoute: typeof ApiCronFootballResolveRoute
  ApiCronFootballSyncRoute: typeof ApiCronFootballSyncRoute
  ApiWebhooksSyncpayRoute: typeof ApiWebhooksSyncpayRoute
  ApiPublicHlsProxySplatRoute: typeof ApiPublicHlsProxySplatRoute
  ApiPublicSnapshotProxySplatRoute: typeof ApiPublicSnapshotProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/sub-affiliates': {
      id: '/partner/sub-affiliates'
      path: '/sub-affiliates'
      fullPath: '/partner/sub-affiliates'
      preLoaderRoute: typeof PartnerSubAffiliatesRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/revenue': {
      id: '/partner/revenue'
      path: '/revenue'
      fullPath: '/partner/revenue'
      preLoaderRoute: typeof PartnerRevenueRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/performance': {
      id: '/partner/performance'
      path: '/performance'
      fullPath: '/partner/performance'
      preLoaderRoute: typeof PartnerPerformanceRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/pending': {
      id: '/partner/pending'
      path: '/pending'
      fullPath: '/partner/pending'
      preLoaderRoute: typeof PartnerPendingRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/payouts': {
      id: '/partner/payouts'
      path: '/payouts'
      fullPath: '/partner/payouts'
      preLoaderRoute: typeof PartnerPayoutsRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/leaderboard': {
      id: '/partner/leaderboard'
      path: '/leaderboard'
      fullPath: '/partner/leaderboard'
      preLoaderRoute: typeof PartnerLeaderboardRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/invites': {
      id: '/partner/invites'
      path: '/invites'
      fullPath: '/partner/invites'
      preLoaderRoute: typeof PartnerInvitesRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/creatives': {
      id: '/partner/creatives'
      path: '/creatives'
      fullPath: '/partner/creatives'
      preLoaderRoute: typeof PartnerCreativesRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/campaigns': {
      id: '/partner/campaigns'
      path: '/campaigns'
      fullPath: '/partner/campaigns'
      preLoaderRoute: typeof PartnerCampaignsRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/analytics': {
      id: '/partner/analytics'
      path: '/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof PartnerAnalyticsRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/simulator': {
      id: '/admin/simulator'
      path: '/simulator'
      fullPath: '/admin/simulator'
      preLoaderRoute: typeof AdminSimulatorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settlement': {
      id: '/admin/settlement'
      path: '/settlement'
      fullPath: '/admin/settlement'
      preLoaderRoute: typeof AdminSettlementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/markets': {
      id: '/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intelligence': {
      id: '/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/football': {
      id: '/admin/football'
      path: '/football'
      fullPath: '/admin/football'
      preLoaderRoute: typeof AdminFootballRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urbanmind': {
      id: '/_app/urbanmind'
      path: '/urbanmind'
      fullPath: '/urbanmind'
      preLoaderRoute: typeof AppUrbanmindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leagues': {
      id: '/_app/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AppLeaguesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/football/': {
      id: '/_app/football/'
      path: '/football'
      fullPath: '/football/'
      preLoaderRoute: typeof AppFootballIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/syncpay': {
      id: '/api/webhooks/syncpay'
      path: '/api/webhooks/syncpay'
      fullPath: '/api/webhooks/syncpay'
      preLoaderRoute: typeof ApiWebhooksSyncpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/football-sync': {
      id: '/api/cron/football-sync'
      path: '/api/cron/football-sync'
      fullPath: '/api/cron/football-sync'
      preLoaderRoute: typeof ApiCronFootballSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/football-resolve': {
      id: '/api/cron/football-resolve'
      path: '/api/cron/football-resolve'
      fullPath: '/api/cron/football-resolve'
      preLoaderRoute: typeof ApiCronFootballResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/markets/create': {
      id: '/_app/markets/create'
      path: '/markets/create'
      fullPath: '/markets/create'
      preLoaderRoute: typeof AppMarketsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/football/$marketId': {
      id: '/_app/football/$marketId'
      path: '/football/$marketId'
      fullPath: '/football/$marketId'
      preLoaderRoute: typeof AppFootballMarketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/$postId': {
      id: '/_app/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof AppFeedPostIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/api/public/snapshot-proxy/$': {
      id: '/api/public/snapshot-proxy/$'
      path: '/api/public/snapshot-proxy/$'
      fullPath: '/api/public/snapshot-proxy/$'
      preLoaderRoute: typeof ApiPublicSnapshotProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hls-proxy/$': {
      id: '/api/public/hls-proxy/$'
      path: '/api/public/hls-proxy/$'
      fullPath: '/api/public/hls-proxy/$'
      preLoaderRoute: typeof ApiPublicHlsProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFootballRoute: typeof AdminFootballRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminSettlementRoute: typeof AdminSettlementRoute
  AdminSimulatorRoute: typeof AdminSimulatorRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFootballRoute: AdminFootballRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminSettlementRoute: AdminSettlementRoute,
  AdminSimulatorRoute: AdminSimulatorRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PartnerRouteRouteChildren {
  PartnerAnalyticsRoute: typeof PartnerAnalyticsRoute
  PartnerCampaignsRoute: typeof PartnerCampaignsRoute
  PartnerCreativesRoute: typeof PartnerCreativesRoute
  PartnerInvitesRoute: typeof PartnerInvitesRoute
  PartnerLeaderboardRoute: typeof PartnerLeaderboardRoute
  PartnerPayoutsRoute: typeof PartnerPayoutsRoute
  PartnerPendingRoute: typeof PartnerPendingRoute
  PartnerPerformanceRoute: typeof PartnerPerformanceRoute
  PartnerRevenueRoute: typeof PartnerRevenueRoute
  PartnerSubAffiliatesRoute: typeof PartnerSubAffiliatesRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteRouteChildren: PartnerRouteRouteChildren = {
  PartnerAnalyticsRoute: PartnerAnalyticsRoute,
  PartnerCampaignsRoute: PartnerCampaignsRoute,
  PartnerCreativesRoute: PartnerCreativesRoute,
  PartnerInvitesRoute: PartnerInvitesRoute,
  PartnerLeaderboardRoute: PartnerLeaderboardRoute,
  PartnerPayoutsRoute: PartnerPayoutsRoute,
  PartnerPendingRoute: PartnerPendingRoute,
  PartnerPerformanceRoute: PartnerPerformanceRoute,
  PartnerRevenueRoute: PartnerRevenueRoute,
  PartnerSubAffiliatesRoute: PartnerSubAffiliatesRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteRouteWithChildren = PartnerRouteRoute._addFileChildren(
  PartnerRouteRouteChildren,
)

interface AppFeedRouteChildren {
  AppFeedPostIdRoute: typeof AppFeedPostIdRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedPostIdRoute: AppFeedPostIdRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppLeaguesRoute: typeof AppLeaguesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUrbanmindRoute: typeof AppUrbanmindRoute
  AppWalletRoute: typeof AppWalletRoute
  AppFootballMarketIdRoute: typeof AppFootballMarketIdRoute
  AppMarketsCreateRoute: typeof AppMarketsCreateRoute
  AppFootballIndexRoute: typeof AppFootballIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRouteWithChildren,
  AppLeaguesRoute: AppLeaguesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUrbanmindRoute: AppUrbanmindRoute,
  AppWalletRoute: AppWalletRoute,
  AppFootballMarketIdRoute: AppFootballMarketIdRoute,
  AppMarketsCreateRoute: AppMarketsCreateRoute,
  AppFootballIndexRoute: AppFootballIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MarketsRouteChildren {
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PartnerRouteRoute: PartnerRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LiveRoute: LiveRoute,
  MarketsRoute: MarketsRouteWithChildren,
  RankingRoute: RankingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RSlugRoute: RSlugRoute,
  ApiCronFootballResolveRoute: ApiCronFootballResolveRoute,
  ApiCronFootballSyncRoute: ApiCronFootballSyncRoute,
  ApiWebhooksSyncpayRoute: ApiWebhooksSyncpayRoute,
  ApiPublicHlsProxySplatRoute: ApiPublicHlsProxySplatRoute,
  ApiPublicSnapshotProxySplatRoute: ApiPublicSnapshotProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
