/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PartnerRouteRouteImport } from './routes/partner/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PartnerSubAffiliatesRouteImport } from './routes/partner/sub-affiliates'
import { Route as PartnerRevenueRouteImport } from './routes/partner/revenue'
import { Route as PartnerPerformanceRouteImport } from './routes/partner/performance'
import { Route as PartnerPayoutsRouteImport } from './routes/partner/payouts'
import { Route as PartnerLeaderboardRouteImport } from './routes/partner/leaderboard'
import { Route as PartnerInvitesRouteImport } from './routes/partner/invites'
import { Route as PartnerCreativesRouteImport } from './routes/partner/creatives'
import { Route as PartnerCampaignsRouteImport } from './routes/partner/campaigns'
import { Route as PartnerAnalyticsRouteImport } from './routes/partner/analytics'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AdminSimulatorRouteImport } from './routes/admin/simulator'
import { Route as AdminSettlementRouteImport } from './routes/admin/settlement'
import { Route as AdminRiskRouteImport } from './routes/admin/risk'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminMarketsRouteImport } from './routes/admin/markets'
import { Route as AdminIntelligenceRouteImport } from './routes/admin/intelligence'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppUrbanmindRouteImport } from './routes/_app/urbanmind'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPositionsRouteImport } from './routes/_app/positions'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMarketsRouteImport } from './routes/_app/markets'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppLeaguesRouteImport } from './routes/_app/leagues'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMarketsIndexRouteImport } from './routes/_app/markets.index'
import { Route as ApiWebhooksSyncpayRouteImport } from './routes/api/webhooks/syncpay'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppMarketsMarketIdRouteImport } from './routes/_app/markets.$marketId'
import { Route as AppFeedPostIdRouteImport } from './routes/_app/feed.$postId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRouteRoute = PartnerRouteRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSubAffiliatesRoute = PartnerSubAffiliatesRouteImport.update({
  id: '/sub-affiliates',
  path: '/sub-affiliates',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerRevenueRoute = PartnerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerPerformanceRoute = PartnerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerPayoutsRoute = PartnerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerLeaderboardRoute = PartnerLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerInvitesRoute = PartnerInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerCreativesRoute = PartnerCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerCampaignsRoute = PartnerCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const PartnerAnalyticsRoute = PartnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PartnerRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSimulatorRoute = AdminSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettlementRoute = AdminSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanmindRoute = AppUrbanmindRouteImport.update({
  id: '/urbanmind',
  path: '/urbanmind',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesRoute = AppLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsIndexRoute = AppMarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMarketsRoute,
} as any)
const ApiWebhooksSyncpayRoute = ApiWebhooksSyncpayRouteImport.update({
  id: '/api/webhooks/syncpay',
  path: '/api/webhooks/syncpay',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppMarketsMarketIdRoute = AppMarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => AppMarketsRoute,
} as any)
const AppFeedPostIdRoute = AppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/partner': typeof PartnerRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/leagues': typeof AppLeaguesRoute
  '/live': typeof AppLiveRoute
  '/markets': typeof AppMarketsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/positions': typeof AppPositionsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/ranking': typeof AppRankingRoute
  '/settings': typeof AppSettingsRoute
  '/urbanmind': typeof AppUrbanmindRoute
  '/wallet': typeof AppWalletRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/creatives': typeof PartnerCreativesRoute
  '/partner/invites': typeof PartnerInvitesRoute
  '/partner/leaderboard': typeof PartnerLeaderboardRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/performance': typeof PartnerPerformanceRoute
  '/partner/revenue': typeof PartnerRevenueRoute
  '/partner/sub-affiliates': typeof PartnerSubAffiliatesRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/markets/$marketId': typeof AppMarketsMarketIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/markets/': typeof AppMarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/leagues': typeof AppLeaguesRoute
  '/live': typeof AppLiveRoute
  '/notifications': typeof AppNotificationsRoute
  '/positions': typeof AppPositionsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/ranking': typeof AppRankingRoute
  '/settings': typeof AppSettingsRoute
  '/urbanmind': typeof AppUrbanmindRoute
  '/wallet': typeof AppWalletRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/creatives': typeof PartnerCreativesRoute
  '/partner/invites': typeof PartnerInvitesRoute
  '/partner/leaderboard': typeof PartnerLeaderboardRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/performance': typeof PartnerPerformanceRoute
  '/partner/revenue': typeof PartnerRevenueRoute
  '/partner/sub-affiliates': typeof PartnerSubAffiliatesRoute
  '/r/$slug': typeof RSlugRoute
  '/admin': typeof AdminIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/markets/$marketId': typeof AppMarketsMarketIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/markets': typeof AppMarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/partner': typeof PartnerRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/leagues': typeof AppLeaguesRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/markets': typeof AppMarketsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/ranking': typeof AppRankingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/urbanmind': typeof AppUrbanmindRoute
  '/_app/wallet': typeof AppWalletRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settlement': typeof AdminSettlementRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/campaigns': typeof PartnerCampaignsRoute
  '/partner/creatives': typeof PartnerCreativesRoute
  '/partner/invites': typeof PartnerInvitesRoute
  '/partner/leaderboard': typeof PartnerLeaderboardRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/performance': typeof PartnerPerformanceRoute
  '/partner/revenue': typeof PartnerRevenueRoute
  '/partner/sub-affiliates': typeof PartnerSubAffiliatesRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/_app/feed/$postId': typeof AppFeedPostIdRoute
  '/_app/markets/$marketId': typeof AppMarketsMarketIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/_app/markets/': typeof AppMarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/partner'
    | '/sitemap.xml'
    | '/dashboard'
    | '/feed'
    | '/leagues'
    | '/live'
    | '/markets'
    | '/notifications'
    | '/positions'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/urbanmind'
    | '/wallet'
    | '/admin/finance'
    | '/admin/intelligence'
    | '/admin/markets'
    | '/admin/partners'
    | '/admin/risk'
    | '/admin/settlement'
    | '/admin/simulator'
    | '/admin/sources'
    | '/admin/system'
    | '/admin/users'
    | '/partner/analytics'
    | '/partner/campaigns'
    | '/partner/creatives'
    | '/partner/invites'
    | '/partner/leaderboard'
    | '/partner/payouts'
    | '/partner/performance'
    | '/partner/revenue'
    | '/partner/sub-affiliates'
    | '/r/$slug'
    | '/admin/'
    | '/partner/'
    | '/feed/$postId'
    | '/markets/$marketId'
    | '/profile/$userId'
    | '/api/webhooks/syncpay'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/dashboard'
    | '/feed'
    | '/leagues'
    | '/live'
    | '/notifications'
    | '/positions'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/urbanmind'
    | '/wallet'
    | '/admin/finance'
    | '/admin/intelligence'
    | '/admin/markets'
    | '/admin/partners'
    | '/admin/risk'
    | '/admin/settlement'
    | '/admin/simulator'
    | '/admin/sources'
    | '/admin/system'
    | '/admin/users'
    | '/partner/analytics'
    | '/partner/campaigns'
    | '/partner/creatives'
    | '/partner/invites'
    | '/partner/leaderboard'
    | '/partner/payouts'
    | '/partner/performance'
    | '/partner/revenue'
    | '/partner/sub-affiliates'
    | '/r/$slug'
    | '/admin'
    | '/partner'
    | '/feed/$postId'
    | '/markets/$marketId'
    | '/profile/$userId'
    | '/api/webhooks/syncpay'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/partner'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/leagues'
    | '/_app/live'
    | '/_app/markets'
    | '/_app/notifications'
    | '/_app/positions'
    | '/_app/profile'
    | '/_app/ranking'
    | '/_app/settings'
    | '/_app/urbanmind'
    | '/_app/wallet'
    | '/admin/finance'
    | '/admin/intelligence'
    | '/admin/markets'
    | '/admin/partners'
    | '/admin/risk'
    | '/admin/settlement'
    | '/admin/simulator'
    | '/admin/sources'
    | '/admin/system'
    | '/admin/users'
    | '/partner/analytics'
    | '/partner/campaigns'
    | '/partner/creatives'
    | '/partner/invites'
    | '/partner/leaderboard'
    | '/partner/payouts'
    | '/partner/performance'
    | '/partner/revenue'
    | '/partner/sub-affiliates'
    | '/r/$slug'
    | '/admin/'
    | '/partner/'
    | '/_app/feed/$postId'
    | '/_app/markets/$marketId'
    | '/_app/profile/$userId'
    | '/api/webhooks/syncpay'
    | '/_app/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PartnerRouteRoute: typeof PartnerRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RSlugRoute: typeof RSlugRoute
  ApiWebhooksSyncpayRoute: typeof ApiWebhooksSyncpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/sub-affiliates': {
      id: '/partner/sub-affiliates'
      path: '/sub-affiliates'
      fullPath: '/partner/sub-affiliates'
      preLoaderRoute: typeof PartnerSubAffiliatesRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/revenue': {
      id: '/partner/revenue'
      path: '/revenue'
      fullPath: '/partner/revenue'
      preLoaderRoute: typeof PartnerRevenueRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/performance': {
      id: '/partner/performance'
      path: '/performance'
      fullPath: '/partner/performance'
      preLoaderRoute: typeof PartnerPerformanceRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/payouts': {
      id: '/partner/payouts'
      path: '/payouts'
      fullPath: '/partner/payouts'
      preLoaderRoute: typeof PartnerPayoutsRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/leaderboard': {
      id: '/partner/leaderboard'
      path: '/leaderboard'
      fullPath: '/partner/leaderboard'
      preLoaderRoute: typeof PartnerLeaderboardRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/invites': {
      id: '/partner/invites'
      path: '/invites'
      fullPath: '/partner/invites'
      preLoaderRoute: typeof PartnerInvitesRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/creatives': {
      id: '/partner/creatives'
      path: '/creatives'
      fullPath: '/partner/creatives'
      preLoaderRoute: typeof PartnerCreativesRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/campaigns': {
      id: '/partner/campaigns'
      path: '/campaigns'
      fullPath: '/partner/campaigns'
      preLoaderRoute: typeof PartnerCampaignsRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/partner/analytics': {
      id: '/partner/analytics'
      path: '/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof PartnerAnalyticsRouteImport
      parentRoute: typeof PartnerRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/simulator': {
      id: '/admin/simulator'
      path: '/simulator'
      fullPath: '/admin/simulator'
      preLoaderRoute: typeof AdminSimulatorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settlement': {
      id: '/admin/settlement'
      path: '/settlement'
      fullPath: '/admin/settlement'
      preLoaderRoute: typeof AdminSettlementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/markets': {
      id: '/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intelligence': {
      id: '/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urbanmind': {
      id: '/_app/urbanmind'
      path: '/urbanmind'
      fullPath: '/urbanmind'
      preLoaderRoute: typeof AppUrbanmindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leagues': {
      id: '/_app/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AppLeaguesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets/': {
      id: '/_app/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof AppMarketsIndexRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/api/webhooks/syncpay': {
      id: '/api/webhooks/syncpay'
      path: '/api/webhooks/syncpay'
      fullPath: '/api/webhooks/syncpay'
      preLoaderRoute: typeof ApiWebhooksSyncpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/markets/$marketId': {
      id: '/_app/markets/$marketId'
      path: '/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof AppMarketsMarketIdRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/_app/feed/$postId': {
      id: '/_app/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof AppFeedPostIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminSettlementRoute: typeof AdminSettlementRoute
  AdminSimulatorRoute: typeof AdminSimulatorRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminSettlementRoute: AdminSettlementRoute,
  AdminSimulatorRoute: AdminSimulatorRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PartnerRouteRouteChildren {
  PartnerAnalyticsRoute: typeof PartnerAnalyticsRoute
  PartnerCampaignsRoute: typeof PartnerCampaignsRoute
  PartnerCreativesRoute: typeof PartnerCreativesRoute
  PartnerInvitesRoute: typeof PartnerInvitesRoute
  PartnerLeaderboardRoute: typeof PartnerLeaderboardRoute
  PartnerPayoutsRoute: typeof PartnerPayoutsRoute
  PartnerPerformanceRoute: typeof PartnerPerformanceRoute
  PartnerRevenueRoute: typeof PartnerRevenueRoute
  PartnerSubAffiliatesRoute: typeof PartnerSubAffiliatesRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteRouteChildren: PartnerRouteRouteChildren = {
  PartnerAnalyticsRoute: PartnerAnalyticsRoute,
  PartnerCampaignsRoute: PartnerCampaignsRoute,
  PartnerCreativesRoute: PartnerCreativesRoute,
  PartnerInvitesRoute: PartnerInvitesRoute,
  PartnerLeaderboardRoute: PartnerLeaderboardRoute,
  PartnerPayoutsRoute: PartnerPayoutsRoute,
  PartnerPerformanceRoute: PartnerPerformanceRoute,
  PartnerRevenueRoute: PartnerRevenueRoute,
  PartnerSubAffiliatesRoute: PartnerSubAffiliatesRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteRouteWithChildren = PartnerRouteRoute._addFileChildren(
  PartnerRouteRouteChildren,
)

interface AppFeedRouteChildren {
  AppFeedPostIdRoute: typeof AppFeedPostIdRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedPostIdRoute: AppFeedPostIdRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppMarketsRouteChildren {
  AppMarketsMarketIdRoute: typeof AppMarketsMarketIdRoute
  AppMarketsIndexRoute: typeof AppMarketsIndexRoute
}

const AppMarketsRouteChildren: AppMarketsRouteChildren = {
  AppMarketsMarketIdRoute: AppMarketsMarketIdRoute,
  AppMarketsIndexRoute: AppMarketsIndexRoute,
}

const AppMarketsRouteWithChildren = AppMarketsRoute._addFileChildren(
  AppMarketsRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppLeaguesRoute: typeof AppLeaguesRoute
  AppLiveRoute: typeof AppLiveRoute
  AppMarketsRoute: typeof AppMarketsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppRankingRoute: typeof AppRankingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUrbanmindRoute: typeof AppUrbanmindRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRouteWithChildren,
  AppLeaguesRoute: AppLeaguesRoute,
  AppLiveRoute: AppLiveRoute,
  AppMarketsRoute: AppMarketsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppRankingRoute: AppRankingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUrbanmindRoute: AppUrbanmindRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PartnerRouteRoute: PartnerRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RSlugRoute: RSlugRoute,
  ApiWebhooksSyncpayRoute: ApiWebhooksSyncpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
