/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppUrbanmindRouteImport } from './routes/_app/urbanmind'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPositionsRouteImport } from './routes/_app/positions'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMarketsRouteImport } from './routes/_app/markets'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppMarketsMarketIdRouteImport } from './routes/_app/markets.$marketId'
import { Route as AppFeedPostIdRouteImport } from './routes/_app/feed.$postId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanmindRoute = AppUrbanmindRouteImport.update({
  id: '/urbanmind',
  path: '/urbanmind',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppMarketsMarketIdRoute = AppMarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => AppMarketsRoute,
} as any)
const AppFeedPostIdRoute = AppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/live': typeof AppLiveRoute
  '/markets': typeof AppMarketsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/positions': typeof AppPositionsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/ranking': typeof AppRankingRoute
  '/settings': typeof AppSettingsRoute
  '/urbanmind': typeof AppUrbanmindRoute
  '/wallet': typeof AppWalletRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/markets/$marketId': typeof AppMarketsMarketIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/live': typeof AppLiveRoute
  '/markets': typeof AppMarketsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/positions': typeof AppPositionsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/ranking': typeof AppRankingRoute
  '/settings': typeof AppSettingsRoute
  '/urbanmind': typeof AppUrbanmindRoute
  '/wallet': typeof AppWalletRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/markets/$marketId': typeof AppMarketsMarketIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/live': typeof AppLiveRoute
  '/_app/markets': typeof AppMarketsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/ranking': typeof AppRankingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/urbanmind': typeof AppUrbanmindRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/feed/$postId': typeof AppFeedPostIdRoute
  '/_app/markets/$marketId': typeof AppMarketsMarketIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/dashboard'
    | '/feed'
    | '/live'
    | '/markets'
    | '/notifications'
    | '/positions'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/urbanmind'
    | '/wallet'
    | '/feed/$postId'
    | '/markets/$marketId'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/dashboard'
    | '/feed'
    | '/live'
    | '/markets'
    | '/notifications'
    | '/positions'
    | '/profile'
    | '/ranking'
    | '/settings'
    | '/urbanmind'
    | '/wallet'
    | '/feed/$postId'
    | '/markets/$marketId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/live'
    | '/_app/markets'
    | '/_app/notifications'
    | '/_app/positions'
    | '/_app/profile'
    | '/_app/ranking'
    | '/_app/settings'
    | '/_app/urbanmind'
    | '/_app/wallet'
    | '/_app/feed/$postId'
    | '/_app/markets/$marketId'
    | '/_app/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urbanmind': {
      id: '/_app/urbanmind'
      path: '/urbanmind'
      fullPath: '/urbanmind'
      preLoaderRoute: typeof AppUrbanmindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/markets/$marketId': {
      id: '/_app/markets/$marketId'
      path: '/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof AppMarketsMarketIdRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/_app/feed/$postId': {
      id: '/_app/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof AppFeedPostIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
  }
}

interface AppFeedRouteChildren {
  AppFeedPostIdRoute: typeof AppFeedPostIdRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedPostIdRoute: AppFeedPostIdRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppMarketsRouteChildren {
  AppMarketsMarketIdRoute: typeof AppMarketsMarketIdRoute
}

const AppMarketsRouteChildren: AppMarketsRouteChildren = {
  AppMarketsMarketIdRoute: AppMarketsMarketIdRoute,
}

const AppMarketsRouteWithChildren = AppMarketsRoute._addFileChildren(
  AppMarketsRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppLiveRoute: typeof AppLiveRoute
  AppMarketsRoute: typeof AppMarketsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppRankingRoute: typeof AppRankingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUrbanmindRoute: typeof AppUrbanmindRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRouteWithChildren,
  AppLiveRoute: AppLiveRoute,
  AppMarketsRoute: AppMarketsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppRankingRoute: AppRankingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUrbanmindRoute: AppUrbanmindRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
