// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

async function ensureSessionToken(): Promise<string | null> {
  // Server-side / SSR: no browser session available.
  if (typeof window === "undefined") return null;

  const { data } = await supabase.auth.getSession();
  return data.session?.access_token ?? null;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = await ensureSessionToken();
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
