// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/start-client-core";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { resolveSupabasePublicEnv } from "./env";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async (options) => {
    const { next } = options;
    const request = (options as unknown as { request?: Request }).request;
    const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } =
      resolveSupabasePublicEnv();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    let userId = claimsData?.claims?.sub as string | undefined;

    if (claimsError || !userId) {
      const { data: userData, error: userError } = await supabase.auth.getUser(token);
      if (userError || !userData.user?.id) {
        throw new Error("Unauthorized: Invalid token");
      }
      userId = userData.user.id;
    }

    return next({
      context: {
        supabase,
        userId,
        claims: claimsData?.claims ?? null,
      },
    });
  },
);
