// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzhffxiicufqcabmhscq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aGZmeGlpY3VmcWNhYm1oc2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNjczNzUsImV4cCI6MjA5NDk0MzM3NX0.mZioGLaEUpRhsl0Hdkcj01GysdYA3nOhOMXj7msTMHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});